### ISSUE TITLE
Kleborate complaining about not finding "Kaptive" folder?

### ISSUE THREAD

**Issue by tseemann** [katholt/Kleborate#13]
```
kleborate -a  Klebsiella_quasipneumoniae.fasta -o KleborateTest -r -s
Error: could not find Kaptive directory. Did you git clone with --recursive?
```

Kaptive is a different piece of software. Is this maybe an undeclared dependency or a cut and paste error?  I did `--recursive` but I don't see any submodules?

I did a `pip2 install` from the dev branch. aka `v2.0`

**Comment by rrwick** [comment]
The development branch (and soon the master branch) does have Kaptive as a submodule, so it is a real error. The question is why you didn't get Kaptive along with Kleborate when you pip installed it.

I just tried this command on my computer, and it worked for me (grabbed both Kleborate and Kaptive, Kleborate ran without an error): 
`pip install --user git+https://github.com/katholt/Kleborate.git@development`

Can you see if that command works?

Ryan

**Comment by tseemann** [comment]
Your pip line worked:
`Successfully installed Kleborate-0.2.0`

I think i must have done this:
```
git clone kaptive
pip2 install kaptive
```
and because it didn't get the submodules - wham.

PS. i  dislike submodules

**Comment by hkaspersen** [comment]
Hello! I just wanted to inform you that I got the same error by installing kleborate through conda. I also had to manually update to blast+ to v. 2.71 (2.5 was installed with kleborate).

**Comment by kelwyres** [comment]
Hi hkaspersen, 

Thanks for your comment. Please note that we don't have ownership of the Kleborate conda environment (it was created by someone else). If you would like to suggest updates, please contact the owners directly.

Thanks,
Kelly
