### ISSUE TITLE
please provide a release tag

### ISSUE THREAD

**Issue by EricDeveaud** [katholt/Kleborate#14]
Hello, 

I was asked to install Kleborate on our cluster.

our policy is to install from tagged release.

can you provide such tag ?

regards

Eric

**Comment by kelwyres** [comment]
Hi Eric, 
We have a few new updates that will be coming to the master branch very soon. We'll do a release as soon as those are ready to go and will let you know.
Thanks,
Kelly

**Comment by rrwick** [comment]
Thanks for your patience, Eric. We've now merged lots of changes to the master branch and made a release of Kleborate!
