### ISSUE TITLE
Plans on using core genome MLST data set

### ISSUE THREAD

**Issue by CptChiler** [katholt/Kleborate#15]
Are there any plans on using the cgMLST data set (http://www.cgmlst.org/ncs/schema/2187931/locus/)?

[Defining and Evaluating a Core Genome Multilocus Sequence Typing Scheme for Whole-Genome Sequence-Based Typing of Klebsiella pneumoniae](https://www.frontiersin.org/articles/10.3389/fmicb.2017.00371/full)

Christian

**Comment by katholt** [comment]
No, as this is a closed system accessible only to SeqSphere+ users.
We will look at supporting the publicly available cgMLST scheme maintained by the Institut Pasteur BIGSdb-Kp which has direct compatibility with the widely used 7-locus MLST scheme. 
See http://bigsdb.pasteur.fr/klebsiella/klebsiella.html https://www.ncbi.nlm.nih.gov/pubmed/25341126
