### ISSUE TITLE
tblastn crashing

### ISSUE THREAD

**Issue by hjb60** [katholt/Kleborate#16]
Hello,

I am using Kleborate as follows:
kleborate --all -o test_results.txt -a *.fa

But getting the following error:
Error: Kaptive failed to run with the following error:
Error: tblastn crashed!

You are using BLAST+ v2.6.0 which may crash when running with multiple threads.

To avoid this issue, try one of the following:
  1) Use an unaffected version of BLAST+ (v2.3.0 or earlier should work)
  2) Run Kaptive with "--threads 1" (will probably be slower)

Is there a way to specify use of a Blast version or a fix for this version?

Many thanks

**Comment by katholt** [comment]
Hiya, we can't do anything about the bugs in threading in BLAST v2.6.0. 
As noted in the error message, you can get around this by using an earlier version of blast without the bug, or switching off threading by setting '--threads 1' in Kaptive.

**Comment by andersgs** [comment]
Right now the way Kleborate is setup one cannot control the numbers of threads passed on to Kaptive. The default for Kaptive is `min(n_cores, 4)`.

Kleborate needs a `--kaptive_threads` option.
