### ISSUE TITLE
setup.py should run makblastdb 

### ISSUE THREAD

**Issue by EricDeveaud** [katholt/Kleborate#18]
Hello, 

in a multi user environment if one admin runs setup.py to install Kleborate, kleborate will be installed in a location where users can't write. 

at first run of kleborate mlstBLAST.py resBLAST.py will check for blast indexes in kleborate data dir and will try to create those index leadin the user to a cryptic err;

```
Error: NCBI C++ Exception:
    T0 /somwhere/blast+/blast+-2.2.40/c++/src/objtools/blast/seqdb_writer/build_db.cpp", line 1001: Error: BLASTDB::ncbi::s_CreateDirectories() - You do not have write permissions on 'data'

Traceback (most recent call last):
  File "/somewhere/Kleborate/0.1.0/lib/python2.7/site-packages/Kleborate-0.1.0-py2.7.egg/kleborate/mlstBLAST.py", line 60, in <module>
    stdout = devnull, shell=True)
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'makeblastdb -dbtype nucl -in /somewhere/Kleborate/0.1.0/lib/python2.7/site-packages/Kleborate-0.1.0-py2.7.egg/kleborate/data/Klebsiella_pneumoniae.fasta' returned non-zero exit status 255
Error: NCBI C++ Exception:
```

I suggest setup.py perform this step as a postinstall step.

users runnig kleborate directly form their own directory won't face this problem.

regards

Eric

**Comment by katholt** [comment]
Yes agreed. We had looked at this earlier but there were some issues with integrating the call into the installation process as well; but it does need to be addressed.
