### ISSUE TITLE
--species argument unrecognized

### ISSUE THREAD

**Issue by Dong-Ning** [katholt/Kleborate#19]
Dear Dr. Holt,

Please ignore my previous message. I have solved the problem by installing the new version. Thanks and sorry for the inconvenience.
-------------------------------------------------------
I installed Kleborate but the --species argument is nonfunctional. Mash is already well installed. Can you help me with this problem? Many thanks!
------------------------------------------------------

Best wishes,
Ning

**Comment by rrwick** [comment]
Glad you got it working!
