### ISSUE TITLE
Check for dependencies

### ISSUE THREAD

**Issue by jhawkey** [katholt/Kleborate#23]
Just ran Kleborate with the --all option, and it got to the Kaptive step and complained "No module named Bio", as Biopython wasn't installed in my environment. It would be good if Kleborate did a check of dependencies it requires, depending on what option has been selected, giving a nice error to the user.

**Comment by rrwick** [comment]
That's a good idea, but I think it's safe to say that Biopython is just a straight-up requirement for Kleborate (even if it's not used if you don't use --resistance or --all).

We've made this clear in the README now and Biopython is now listed in Kleborate's `requirements.txt` file, so I'm going to call this one closed. Feel free to reopen it if you disagree :smile:
