### ISSUE TITLE
tblastn crashing cannot be avoided when running Kleborate.

### ISSUE THREAD

**Issue by pmenzel** [katholt/Kleborate#24]
Hi and thanks for the nice tool!

I just encountered the same problem as in #16, using blast 2.9.0.

It's probably easiest to just set the default number of threads for Kaptive to 1 when it is called from within Kleborate, since nowadays most people probably use a newer blast version than 2.3.0.

PS: the version number [check](https://github.com/katholt/Kaptive/blob/013e30616696308a827fa7ebaa1f54991148188b/kaptive.py#L904) in Kaptive does not consider newer blast versions.

all the best

**Comment by katholt** [comment]
Thanks, this fix is implemented in the latest version.
