### ISSUE TITLE
ModuleNotFoundError: No module named 'Bio'

### ISSUE THREAD

**Issue by hrfontana** [katholt/Kleborate#26]
Hi! 

I have been trying to use Kleborate but it gives me back 

Error: Kaptive failed to run with the following error:
Traceback (most recent call last):
  File "/home/hfontana/anaconda3/envs/kleborate/lib/python3.7/site-packages/kaptive/kaptive.py", line 49, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'

I tried to install by wget (github installation guide) and by conda (conda install -c bioconda kleborate) but either options resulted unsuccessful 

Thanks in advance

**Comment by tillea** [comment]
Sounds like you are lacking BioPython.  On a Deb-based system try `apt-get install python3-biopython`.

**Comment by hrfontana** [comment]
Hello! I noted that only the option --all does not work.

I tried your suggestion: 
"sudo apt-get install python3-biopython
[sudo] password for hfontana: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python-biopython python-biopython-doc python-olefile python-pil
  python-renderpm python-reportlab python-reportlab-accel python3-numpy
Suggested packages:
  python-tk clustalo clustalw dssp fasttree mafft muscle phylip phyml prank
  probcons python-mysqldb python-matplotlib python-psycopg2 python-scipy raxml
  t-coffee wise w3-dtd-mathml python-pil-doc python-pil-dbg
  python-renderpm-dbg python-egenix-mxtexttools python-reportlab-doc
  python3-tk python3-mysqldb python3-matplotlib python3-rdflib
  python3-psycopg2 python3-scipy gfortran python-numpy-doc python3-dev
  python3-pytest python3-numpy-dbg
The following NEW packages will be installed:
  python-biopython python-biopython-doc python-olefile python-pil
  python-renderpm python-reportlab python-reportlab-accel python3-biopython
  python3-numpy
0 upgraded, 9 newly installed, 0 to remove and 12 not upgraded.
Need to get 19,8 MB of archives.
After this operation, 52,5 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
0% [Working]
Get:1 http://br.archive.ubuntu.com/ubuntu disco/main amd64 python-pil amd64 5.4.1-1 [338 kB]
Get:2 http://br.archive.ubuntu.com/ubuntu disco/universe amd64 python-reportlab-accel amd64 3.5.18-1 [22,9 kB]
Get:3 http://br.archive.ubuntu.com/ubuntu disco/universe amd64 python-reportlab all 3.5.18-1 [529 kB]
Get:4 http://br.archive.ubuntu.com/ubuntu disco/universe amd64 python-biopython amd64 1.73+dfsg-1ubuntu1 [1.330 kB]
Get:5 http://br.archive.ubuntu.com/ubuntu disco/universe amd64 python-biopython-doc all 1.73+dfsg-1ubuntu1 [14,1 MB]
Get:6 http://br.archive.ubuntu.com/ubuntu disco/main amd64 python-olefile all 0.46-1 [33,6 kB]
Get:7 http://br.archive.ubuntu.com/ubuntu disco/universe amd64 python-renderpm amd64 3.5.18-1 [59,7 kB]
Get:8 http://br.archive.ubuntu.com/ubuntu disco/main amd64 python3-numpy amd64 1:1.16.2-1ubuntu1 [2.106 kB]
Get:9 http://br.archive.ubuntu.com/ubuntu disco/universe amd64 python3-biopython amd64 1.73+dfsg-1ubuntu1 [1.283 kB]
Fetched 19,8 MB in 29s (685 kB/s)                                              
Selecting previously unselected package python-pil:amd64.
(Reading database ... 189441 files and directories currently installed.)
Preparing to unpack .../0-python-pil_5.4.1-1_amd64.deb ...
Unpacking python-pil:amd64 (5.4.1-1) ...
Selecting previously unselected package python-reportlab-accel:amd64.
Preparing to unpack .../1-python-reportlab-accel_3.5.18-1_amd64.deb ...
Unpacking python-reportlab-accel:amd64 (3.5.18-1) ...
Selecting previously unselected package python-reportlab.
Preparing to unpack .../2-python-reportlab_3.5.18-1_all.deb ...
Unpacking python-reportlab (3.5.18-1) ...
Selecting previously unselected package python-biopython.
Preparing to unpack .../3-python-biopython_1.73+dfsg-1ubuntu1_amd64.deb ...
Unpacking python-biopython (1.73+dfsg-1ubuntu1) ...
Selecting previously unselected package python-biopython-doc.
Preparing to unpack .../4-python-biopython-doc_1.73+dfsg-1ubuntu1_all.deb ...
Unpacking python-biopython-doc (1.73+dfsg-1ubuntu1) ...
Selecting previously unselected package python-olefile.
Preparing to unpack .../5-python-olefile_0.46-1_all.deb ...
Unpacking python-olefile (0.46-1) ...
Selecting previously unselected package python-renderpm:amd64.
Preparing to unpack .../6-python-renderpm_3.5.18-1_amd64.deb ...
Unpacking python-renderpm:amd64 (3.5.18-1) ...
Selecting previously unselected package python3-numpy.
Preparing to unpack .../7-python3-numpy_1%3a1.16.2-1ubuntu1_amd64.deb ...
Unpacking python3-numpy (1:1.16.2-1ubuntu1) ...
Selecting previously unselected package python3-biopython.
Preparing to unpack .../8-python3-biopython_1.73+dfsg-1ubuntu1_amd64.deb ...
Unpacking python3-biopython (1.73+dfsg-1ubuntu1) ...
Setting up python-pil:amd64 (5.4.1-1) ...
Setting up python-renderpm:amd64 (3.5.18-1) ...
Setting up python3-numpy (1:1.16.2-1ubuntu1) ...
Setting up python-biopython-doc (1.73+dfsg-1ubuntu1) ...
Setting up python-reportlab-accel:amd64 (3.5.18-1) ...
Setting up python3-biopython (1.73+dfsg-1ubuntu1) ...
Setting up python-olefile (0.46-1) ...
Setting up python-reportlab (3.5.18-1) ...
Setting up python-biopython (1.73+dfsg-1ubuntu1) ...
(kleborate/) hfontana@hfontana:~/anaconda3/envs$ cd /home/hfontana/Documents/thais_UNIFESP/
(kleborate/) hfontana@hfontana:~/Documents/thais_UNIFESP$ kleborate --all -o results.txt -a *.fsa
strain	species	ST	virulence_score	resistance_score	Yersiniabactin	YbST	Colibactin	CbST	Aerobactin	AbST	Salmochelin	SmST	rmpA	rmpA2	wzi	K_locus	K_locus_confidence	O_locus	O_locus_confidence	AGly	Col	Fcyn	Flq	Gly	MLS	Ntmdz	Phe	Rif	Sul	Tet	Tmt	Bla	Bla_Carb	Bla_ESBL	Bla_ESBL_inhR	Bla_broad	Bla_broad_inhR
Error: Kaptive failed to run with the following error:
Traceback (most recent call last):
  File "/home/hfontana/anaconda3/envs/kleborate/lib/python3.7/site-packages/kaptive/kaptive.py", line 49, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'"

When I run only the -r option, it works

kleborate -r -o results.txt -a *fsa
strain	ST	virulence_score	resistance_score	Yersiniabactin	YbST	Colibactin	CbST	Aerobactin	AbST	Salmochelin	SmST	rmpA	rmpA2	wzi	K_locus	AGly	Col	Fcyn	Flq	Gly	MLS	Ntmdz	Phe	Rif	Sul	Tet	Tmt	Bla	Bla_Carb	Bla_ESBL	Bla_ESBL_inhR	Bla_broad	Bla_broad_inhR
105	ST437	0	2	-	0	-	0	-	0	-0	-	-	wzi109	KL36	Aph3-Ia*;AadA2	-	-	QnrB5*;GyrA-83I;ParC-80I	-	MphA	-	CatB4;CatA1*	-	SulI	TetA	DfrA30*	AmpH*;OXA-1	KPC-2	CTX-M-15	-	SHV-11	-

**Comment by hrfontana** [comment]
Thanks in advance

**Comment by hrfontana** [comment]
the problem seens to be with kaptive

**Comment by tillea** [comment]
Hmmm, the latest download has no kaptive.py.  But BioPython is used in some of the scripts in scripts/ dir.

**Comment by katholt** [comment]
Hi guys. We have pushed a new version to master that will shortly be released as v1.0.
The new version is Python3 only and the readme now makes clear that BioPython is required.
