### ISSUE TITLE
Run time test suite does not work

### ISSUE THREAD

**Issue by tillea** [katholt/Kleborate#28]
Hi,
I tried to run the test.sh script you are providing inside your download tarball of Verison 0.3.0.  This leads to

    $ kleborate -p . -o details.txt *.fna
    usage: kleborate -a ASSEMBLIES [ASSEMBLIES ...] [-r] [-s] [--kaptive_k]
                     [--kaptive_o] [-k] [--all] [-o OUTFILE]
                     [--kaptive_k_outfile KAPTIVE_K_OUTFILE]
                     [--kaptive_o_outfile KAPTIVE_O_OUTFILE] [-h] [--version]
    kleborate: error: the following arguments are required: -a/--assemblies

after the data are successfully downloaded.
Could you please comment on this?
Kind regards, Andreas.

**Comment by katholt** [comment]
Hi Andreas, 
Apologies for the delay in replying.
We have been working on substantial code changes, including a proper test suite, which are now available in the master branch.
Please let us know if you are still having issues.
Kat
