### ISSUE TITLE
Problems with version 0.4.0-beta

### ISSUE THREAD

**Issue by safrye** [katholt/Kleborate#29]
Hi,

I updated from version 0.3.0 to 0.4.0-beta because the older version had a problem with the correct identification of one MLST. Therefore I wanted to try out the new getmlst.py script.
Installing the new version worked fine but a run with ncbi-blast+ version 2.7.1 gave the following error:

Critical: (109.6) [tblastn] CObject::RemoveLastReference: CObject is corrupted

Updating to ncb-blast version 2.9.1+ cleared this problem.

The second problem I ran in now is that kleborate crashes when encountering the first non-klebsiella genome. Is this maybe due to the new "fixed error in MLST for non-KpSC"???
The error message I got was:

Traceback (most recent call last):
  File "/home/sfrye/miniconda3/bin/kleborate", line 11, in <module>
    load_entry_point('Kleborate==0.4.0b0', 'console_scripts', 'kleborate')()
  File "/home/sfrye/miniconda3/lib/python3.6/site-packages/kleborate/kleborate.py", line 69, in main
    output_results(stdout_header, full_header, args.outfile, results)
  File "/home/sfrye/miniconda3/lib/python3.6/site-packages/kleborate/kleborate.py", line 528, in output_results
    print('\t'.join([results[x] for x in stdout_header]))
  File "/home/sfrye/miniconda3/lib/python3.6/site-packages/kleborate/kleborate.py", line 528, in <listcomp>
    print('\t'.join([results[x] for x in stdout_header]))
KeyError: 'ST'

With greetings from Norway,
Stephan

**Comment by katholt** [comment]
Yes the KeyError: 'ST' should be fixed now, please pull again and try.

Not sure about the BLAST problem - we have endless troubles keeping code working with different versions of BLAST!

Can you please run the unit tests described here? https://github.com/katholt/Kleborate/tree/master/test

cd Kleborate
python3 -m unittest

**Comment by katholt** [comment]
Just realised the BLAST+ error with 2.7 might be to do with the index in the repo being created with BLAST+ 2.9. If you delete the indexes on kleborate/data/Klebsiella_pneumoniae.fasta and re-run with ncbi-blast+ version 2.7.1 does it work?

**Comment by katholt** [comment]
(Sorry for these requests - it's evening here and I can't test the blast index theory myself, but trying to get you up and running quickly)

**Comment by safrye** [comment]
No problem. I will run the test after lunch. :)

**Comment by safrye** [comment]
Unittest came up with:
Ran 123 tests in 86.454s
OK

I completely removed BLAST+ 2.9, installed version 2.7 and removed the file kleborate/data/Klebsiella_pneumoniae.fasta. The analysis is running now and hasn't crashed, until now. :) I shall report later.

**Comment by katholt** [comment]
Hi Stephan,
I tested the latest code today with BLAST+ 2.7.1 and 2.9.0 and both worked fine including with Kaptive switched on... So I am not sure what is up with the issue you had.
Given this, and that unit tests worked, I'm hoping that the latest code update has resolved the problem. Please let me know if you have any further issues.
Kat

**Comment by aspitaleri** [comment]
Hi,
the latest version is 1.0.0 (both in github and bioconda) but kleborate --version returns 0.4.0
why?
