### ISSUE TITLE
Kleborate AMR

### ISSUE THREAD

**Issue by CatherineLud** [katholt/Kleborate#32]
I submitted an assembly to pathogenwatch and the NDM-1 gene was not detected using Kleborate, however the gene was detected by PCR performed by the reference laboratory and using resfinder (see attached). Can you provide information on why this gene was not found using Kleborate? If you would like to see the sequence, can you please provide me with an e-mail address as I would like to keep the sequence private.
Best wishes,
Catherine
![K0923](https://user-images.githubusercontent.com/59051606/71168399-e7d13200-2256-11ea-9f96-62c11fad4b88.png)

**Comment by katholt** [comment]
Hi Catherine, this sounds unusual and I don't know why it would not be reported if the assembly contains blast hit with 100% coverage 99.63% identity, which appears to be the case from the screenshot... If you would like to email me the sequence at drkatholt@gmail.com we can look into it.

**Comment by rrwick** [comment]
Hi Catherine,

I think I've got to the bottom of this one! Short version: while this gene is in your assembly, its sequence glitches out in the middle which has prevented it from getting into Kleborate results. So it's ultimately a matter of assembly quality.

Long version: While your assembly does have the NDM-1 gene at 100% coverage with a _gapped_ alignment, there is a gap (and an ambiguous base) in the gene sequence:

```
reference NDM-1 sequence:   ...GGGTTTCGGGGCA...
SE_K0923_64contig sequence: ...GGGTT-S-GGGCA...
```

Kleborate uses _ungapped_ alignments for its resistance gene search so this means there are two alignments for this gene, one with ~26% coverage (everything before the gap) and one with ~74% coverage (everything after the gap). Both of these fall below Kleborate's coverage threshold for resistance genes (80%) so the hits are tossed out.

It isn't ideal, but I don't think Kleborate needs to change here. It's just a matter of a not-so-great assembly failing to include a complete sequence for a gene that is present (and there are plenty of other ways that can happen as well).

As a side note - how did you make this assembly? I also noticed that it had a lot of contigs which contain nothing but a string of N bases, which led to some BLAST warnings when running Kleborate.

Ryan

**Comment by CatherineLud** [comment]
Dear Ryan,

Is it possible that Kleborate could use a gapped alignment to prevent
misidentification of resistance (given the fact that we know these issues
can arise due to assemblers), similar to what was observed in this case?
For this isolate, laboratory testing and PCR was performed previously and
the gene was detected. It is important from a European Public Health
perspective that we no do miss any resistance genes.

Best wishes,

Catherine
