### ISSUE TITLE
Make pip installable.

### ISSUE THREAD

**Issue by andersgs** [katholt/Kleborate#4]
It would great to be able to install it through pip. For example:

`pip install --user git+https://github.com/katholt/Kleborate.git`

Anders.

**Comment by katholt** [comment]
Yep, thanks Anders. Ryan has that, amongst other user-friendly install/testing/dependency checking stuff, on his to-do list.

**Comment by rrwick** [comment]
Thanks! I've merged this into Kleborate's new development branch.

**Comment by tseemann** [comment]
@rrwick are you planning to move this into master branch?

**Comment by rrwick** [comment]
Sorry, I didn't mention it here, but these changes have been in the master branch for a while.

I just tried the pip line Anders mentioned at the top of this issue, and it worked nicely!
