### ISSUE TITLE
Bio.Alphabet

### ISSUE THREAD

**Issue by mushalallam** [katholt/Kleborate#43]
kleborate -h
/home/nscf/anaconda3/envs/py3/lib/python3.6/site-packages/Bio/SubsMat/__init__.py:131: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  BiopythonDeprecationWarning,
Traceback (most recent call last):
  File "/home/nscf/anaconda3/envs/py3/bin/kleborate", line 7, in <module>
    from kleborate.kleborate import main
  File "/home/nscf/anaconda3/envs/py3/lib/python3.6/site-packages/kleborate/kleborate.py", line 28, in <module>
    from .resBLAST import read_class_file, get_res_headers, resblast_one_assembly
  File "/home/nscf/anaconda3/envs/py3/lib/python3.6/site-packages/kleborate/resBLAST.py", line 25, in <module>
    from .truncation import truncation_check
  File "/home/nscf/anaconda3/envs/py3/lib/python3.6/site-packages/kleborate/truncation.py", line 16, in <module>
    from Bio.Alphabet import IUPAC
  File "/home/nscf/anaconda3/envs/py3/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Comment by rrwick** [comment]
Hi Mushal, thanks for bringing this to our attention!

The most recent version of BioPython has changed a bit, leading to the error you have. I assume you are using BioPython v1.78?

We've fixed this in the [development branch of Kleborate](https://github.com/katholt/Kleborate/tree/development) which will become a new version in the master branch in the not-too-distant future. So if it's not urgent, just wait for the next release and it should work.

If it is urgent, you have two options: either install Kleborate from the development branch to get a preview of the coming release. Or downgrade your copy of BioPython to an earlier version (v1.77 should work I think).

I'll close this issue now, but feel free to reopen it if you're still having issues.

Ryan
