### ISSUE TITLE
Biophyton_problem

### ISSUE THREAD

**Issue by MariaPerezVazquez** [katholt/Kleborate#44]
I am using conda to install kleborate 1.0.0, when I try to use it, I get teh following error 

/home/mperezv/miniconda3/envs/kleborate/lib/python3.8/site-packages/Bio/SubsMat/__init__.py:126: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  warnings.warn(
Traceback (most recent call last):
  File "/home/mperezv/miniconda3/envs/kleborate/bin/kleborate", line 7, in <module>
    from kleborate.kleborate import main
  File "/home/mperezv/miniconda3/envs/kleborate/lib/python3.8/site-packages/kleborate/kleborate.py", line 28, in <module>
    from .resBLAST import read_class_file, get_res_headers, resblast_one_assembly
  File "/home/mperezv/miniconda3/envs/kleborate/lib/python3.8/site-packages/kleborate/resBLAST.py", line 25, in <module>
    from .truncation import truncation_check
  File "/home/mperezv/miniconda3/envs/kleborate/lib/python3.8/site-packages/kleborate/truncation.py", line 16, in <module>
    from Bio.Alphabet import IUPAC
  File "/home/mperezv/miniconda3/envs/kleborate/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

Any help will be great
All the best

**Comment by rrwick** [comment]
Hi Maria,

Thanks for the report! This is the same problem as described in issue #43, so head over there to see the fix.

Ryan

**Comment by MariaPerezVazquez** [comment]
Hi Ryan
I have done upgrade to biophyton 1.77 and I have the same error

ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

Thanks

**Comment by MariaPerezVazquez** [comment]
Hi Ryan
I have done upgrade to biophyton 1.77 and I have the same error

ImportError: Bio.Alphabet has been removed from Biopython. In many cases,
the alphabet can simply be ignored and removed from scripts. In a few
cases, you may need to specify the molecule_type as an annotation on a
SeqRecord for your script to work correctly. Please see
https://biopython.org/wiki/Alphabet for more information.

Thanks
