### ISSUE TITLE
Broken link for preparing resistance gene database files.

### ISSUE THREAD

**Issue by marjorie2205** [katholt/Kleborate#47]
Hi,

I've been trying to prepare the resistance gene database files for Kleborate. I find that the link to the Lahey Clinic beta-lactamase classifications goes nowhere - I have tried google but can't find anything that looks like what I need.

Thanks for your help,
Marjorie

**Comment by marlam89** [comment]
Hi Marjorie, 

Thank you alerting us to this, and we have now removed this previously-working link. Note that these Lahey classifications are in use and being maintained through BLDB. 

Thanks,
Margaret
