### ISSUE TITLE
kaptive.py :: popen uses potentialy wrong python3

### ISSUE THREAD

**Issue by EricDeveaud** [katholt/Kleborate#49]
Hello,

in our setup we have python tools installed with specific python(2|3) that are not in the user path

so we have this error

```
bigmess:Kleborate/2.0.0 > kleborate -k -o details.txt -a ../../datas/Kleborate/Vibrio_cholerae_O1_biovar_eltor_str_N16961_v2.fasta
strain	species	ST	virulence_score	Yersiniabactin	YbST	Colibactin	CbST	Aerobactin	AbST	Salmochelin	SmST	RmpADC	RmST	rmpA2	wzi	K_locus	K_locus_confidence	O_locus	O_locus_confidence
Error: Kaptive failed to run with the following error:
/bin/sh: python3: command not found
```

it is good practive to use the exatct same interpreter the script is running to perform subcalls
fix is quite easy: https://github.com/katholt/Kleborate/pull/48

regards

Eric

**Comment by rrwick** [comment]
Hi Eric,

Thanks for the PR - I've merged it in, so hopefully this will resolve the problem! I'll optimistically close this issue now, but please let me know if the problem persists.

Ryann
