### ISSUE TITLE
unit tests fail with v2.3.0

### ISSUE THREAD

**Issue by kapsakcj** [katholt/Kleborate#67]
Hi I recently upgraded to v2.3.0 and noticed that the included unit tests are now failing, where they previously ran successfully with v2.2.0

The consistent error seen throughout the output of `python3 -m pytest` have been similar to this, with varying sub-directories (the subdirs after `test/`):
```
----------------------------- Captured stderr call -----------------------------
BLAST options error: File test/test_res_mgrb_pmrb/data/CARD_v3.1.13.fasta does not exist
```

kleborate itself still runs successfully, so not a huge deal to fix, but thought I would let you all know!

Curtis

**Comment by rrwick** [comment]
Hi Curtis,

Thanks for letting us know! We recently updated the CARD database and forgot to change the filenames in the tests.

We've made the fix (renamed `test/*/data/CARD_v3.0.8.fasta` files to `test/*/data/CARD_v3.1.13.fasta`) and all tests are now passing. I'll made a new release (v2.3.1) with this fix.

Ryan

**Comment by kapsakcj** [comment]
Great, thank you!
