### ISSUE TITLE
Genotypes of publicly available strains?

### ISSUE THREAD

**Issue by MrOlm** [katholt/Kleborate#8]
Hello,

In the README, it states that a table of pre-computed yersiniabactin, colibactin, capsule locus and chromosomal MLST assignments for 2500 public Klebs genomes is provided in the /data directory.

I was able to find a file that seems to be what this is referring to:

Kleborate/data/Genotyped_Isolates_Lam2017.txt

But as far as I can tell, the file only show the overall sequence type, not the alleles of each of the housekeeping genes (as is provided by kleborate)  

Is there another file with that information? And if not, would it be possible to upload one? It would be particular useful if the file was in the same format at that generated by Kleborate so that I could test my installation to make sure it's getting the same results.

Thank you,
-Matt

**Comment by rrwick** [comment]
Okay, I've just used [this tool](https://github.com/kblin/ncbi-genome-download) to get all of the _Klebsiella_ assemblies on NCBI, and I then ran Kleborate on all of them.

The results are in this file:
https://github.com/katholt/Kleborate/blob/master/data/ncbi_genome_kleborate_results

The first 21 columns of the table are the NCBI metadata. The remaining columns are Kleborate's output. Hope it's useful!

**Comment by MrOlm** [comment]
Hi Ryan,

Thank you for the help. Much appreciated.

I notice that a fair number of genomes have ST "0", which is what I've seen as well. Do you have idea of how accurate kleborate's MLST sequence-type predictions are in general?

Thanks,
-Matt

**Comment by rrwick** [comment]
I haven't examined it closely, but I'd guess that it's about as accurate as any other tool which operates on assemblies. It's essentially doing the same thing as @tseemann's [MLST tool](https://github.com/tseemann/mlst), so I'd expect you'd get the same results with that one.

It seems like most of the "0" STs in this table are some other species of _Klebsiella_ (not _pneumoniae_). That might have been a bit confusing on our part: Kleborate is really designed for _K. pneumoniae_, but I included all _Klebsiella_ in that table.

One other thought: if you have the raw reads, calling ST from those might be better, especially if the assemblies aren't very good. [SRST2](https://github.com/katholt/srst2) is one tool for that, [ARIBA](https://github.com/sanger-pathogens/ariba/wiki) is another.
